// jev_tile_2x2.v -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_tile_2x2`.
// 217 LUT4 cells, 106 word PEs, 105 registers, 6 combinational levels.
// Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
// from the settled levels; rst (synchronous) loads the fabric's initial state.
// Jev microcode ROM `e0_0_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_159 rom_160)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `e0_0_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_161 rom_162)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `e0_0_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_163)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1
// Jev microcode ROM `e0_1_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_232 rom_233)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `e0_1_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_234 rom_235)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `e0_1_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_236)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1
// Jev microcode ROM `e1_0_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_306 rom_307)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `e1_0_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_308 rom_309)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `e1_0_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_310)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1
// Jev microcode ROM `e1_1_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_379 rom_380)
//   state  answer        p      code
//   0      x0            1.000  00
//   1      x1            1.000  01
//   2      x2            1.000  10
//   3      x3            1.000  11
// Jev microcode ROM `e1_1_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_381 rom_382)
//   state  answer        p      code
//   0      w0            1.000  00
//   1      w1            1.000  01
//   2      w2            1.000  10
//   3      w3            1.000  11
// Jev microcode ROM `e1_1_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_383)
//   state  answer        p      code
//   0      mac           1.000  1
//   1      mac           1.000  1
//   2      mac           1.000  1
//   3      mac           1.000  1

`timescale 1ns/1ps
module jev_tile_2x2 (
  input  wire        clk,
  input  wire        rst,
  input  wire w_we,
  input  wire [7:0] w_addr,
  input  wire [31:0] w_data,
  input  wire x_we,
  input  wire [1:0] x_k,
  input  wire [31:0] x0,
  input  wire [31:0] x1,
  input  wire x_go,
  input  wire y_ready,
  output wire x_ready,
  output wire [31:0] y0,
  output wire [31:0] y1,
  output wire y_valid
);

  function lut4(input [15:0] t, input [3:0] i);  // a LUT4 cell: row i of truth table t
    lut4 = t[i];
  endfunction

  // registers
  reg [31:0] wt0 = 32'h00000000;
  reg [31:0] wt1 = 32'h00000000;
  reg [31:0] wt2 = 32'h00000000;
  reg [31:0] wt3 = 32'h00000000;
  reg [31:0] wt4 = 32'h00000000;
  reg [31:0] wt5 = 32'h00000000;
  reg [31:0] wt6 = 32'h00000000;
  reg [31:0] wt7 = 32'h00000000;
  reg [31:0] wt8 = 32'h00000000;
  reg [31:0] wt9 = 32'h00000000;
  reg [31:0] wt10 = 32'h00000000;
  reg [31:0] wt11 = 32'h00000000;
  reg [31:0] wt12 = 32'h00000000;
  reg [31:0] wt13 = 32'h00000000;
  reg [31:0] wt14 = 32'h00000000;
  reg [31:0] wt15 = 32'h00000000;
  reg pend = 1'h0;
  reg [31:0] xs0_0 = 32'h00000000;
  reg [31:0] xa0_0 = 32'h00000000;
  reg [31:0] xs0_1 = 32'h00000000;
  reg [31:0] xa0_1 = 32'h00000000;
  reg [31:0] xs0_2 = 32'h00000000;
  reg [31:0] xa0_2 = 32'h00000000;
  reg [31:0] xs0_3 = 32'h00000000;
  reg [31:0] xa0_3 = 32'h00000000;
  reg [31:0] xs1_0 = 32'h00000000;
  reg [31:0] xa1_0 = 32'h00000000;
  reg [31:0] xs1_1 = 32'h00000000;
  reg [31:0] xa1_1 = 32'h00000000;
  reg [31:0] xs1_2 = 32'h00000000;
  reg [31:0] xa1_2 = 32'h00000000;
  reg [31:0] xs1_3 = 32'h00000000;
  reg [31:0] xa1_3 = 32'h00000000;
  reg e0_0_state_0 = 1'h0;
  reg e0_0_state_1 = 1'h0;
  reg e0_0_o_valid = 1'h0;
  reg e0_0_o_mac = 1'h0;
  reg e0_0_o_last = 1'h0;
  reg e0_0_s_valid = 1'h0;
  reg e0_0_s_mac = 1'h0;
  reg e0_0_s_last = 1'h0;
  reg e0_0_r_valid = 1'h0;
  reg [31:0] e0_0_o_p = 32'h00000000;
  reg [31:0] e0_0_s_p = 32'h00000000;
  reg [31:0] e0_0_acc = 32'h00000000;
  reg [31:0] e0_0_res = 32'h00000000;
  reg e0_0_a_valid = 1'h0;
  reg e0_0_a_mac = 1'h0;
  reg e0_0_a_last = 1'h0;
  reg [31:0] e0_0_a_x = 32'h00000000;
  reg [31:0] e0_0_a_w = 32'h00000000;
  reg e0_1_state_0 = 1'h0;
  reg e0_1_state_1 = 1'h0;
  reg e0_1_o_valid = 1'h0;
  reg e0_1_o_mac = 1'h0;
  reg e0_1_o_last = 1'h0;
  reg e0_1_s_valid = 1'h0;
  reg e0_1_s_mac = 1'h0;
  reg e0_1_s_last = 1'h0;
  reg e0_1_r_valid = 1'h0;
  reg [31:0] e0_1_o_p = 32'h00000000;
  reg [31:0] e0_1_s_p = 32'h00000000;
  reg [31:0] e0_1_acc = 32'h00000000;
  reg [31:0] e0_1_res = 32'h00000000;
  reg e0_1_a_valid = 1'h0;
  reg e0_1_a_mac = 1'h0;
  reg e0_1_a_last = 1'h0;
  reg [31:0] e0_1_a_x = 32'h00000000;
  reg [31:0] e0_1_a_w = 32'h00000000;
  reg e1_0_state_0 = 1'h0;
  reg e1_0_state_1 = 1'h0;
  reg e1_0_o_valid = 1'h0;
  reg e1_0_o_mac = 1'h0;
  reg e1_0_o_last = 1'h0;
  reg e1_0_s_valid = 1'h0;
  reg e1_0_s_mac = 1'h0;
  reg e1_0_s_last = 1'h0;
  reg e1_0_r_valid = 1'h0;
  reg [31:0] e1_0_o_p = 32'h00000000;
  reg [31:0] e1_0_s_p = 32'h00000000;
  reg [31:0] e1_0_acc = 32'h00000000;
  reg [31:0] e1_0_res = 32'h00000000;
  reg e1_0_a_valid = 1'h0;
  reg e1_0_a_mac = 1'h0;
  reg e1_0_a_last = 1'h0;
  reg [31:0] e1_0_a_x = 32'h00000000;
  reg [31:0] e1_0_a_w = 32'h00000000;
  reg e1_1_state_0 = 1'h0;
  reg e1_1_state_1 = 1'h0;
  reg e1_1_o_valid = 1'h0;
  reg e1_1_o_mac = 1'h0;
  reg e1_1_o_last = 1'h0;
  reg e1_1_s_valid = 1'h0;
  reg e1_1_s_mac = 1'h0;
  reg e1_1_s_last = 1'h0;
  reg e1_1_r_valid = 1'h0;
  reg [31:0] e1_1_o_p = 32'h00000000;
  reg [31:0] e1_1_s_p = 32'h00000000;
  reg [31:0] e1_1_acc = 32'h00000000;
  reg [31:0] e1_1_res = 32'h00000000;
  reg e1_1_a_valid = 1'h0;
  reg e1_1_a_mac = 1'h0;
  reg e1_1_a_last = 1'h0;
  reg [31:0] e1_1_a_x = 32'h00000000;
  reg [31:0] e1_1_a_w = 32'h00000000;

  // level 0
  wire dec_lo_19 = lut4(16'h0001, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_hi_20 = lut4(16'h0001, {w_addr[7], w_addr[6], w_addr[5], w_addr[4]});
  wire dec_lo_21 = lut4(16'h0002, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_22 = lut4(16'h0004, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_23 = lut4(16'h0008, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_24 = lut4(16'h0010, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_25 = lut4(16'h0020, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_26 = lut4(16'h0040, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_27 = lut4(16'h0080, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_28 = lut4(16'h0100, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_29 = lut4(16'h0200, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_30 = lut4(16'h0400, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_31 = lut4(16'h0800, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_32 = lut4(16'h1000, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_33 = lut4(16'h2000, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_34 = lut4(16'h4000, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire dec_lo_35 = lut4(16'h8000, {w_addr[3], w_addr[2], w_addr[1], w_addr[0]});
  wire xnor_100 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, x_k[0]});
  wire xnor_101 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, x_k[1]});
  wire xnor_104 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, x_k[0]});
  wire xnor_105 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, x_k[1]});
  wire xnor_108 = lut4(16'h9999, {1'b0, 1'b0, 1'b0, x_k[0]});
  wire xnor_109 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, x_k[1]});
  wire xnor_112 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, x_k[0]});
  wire xnor_113 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, x_k[1]});
  wire rom_159 = lut4(16'hAAAA, {1'b0, 1'b0, e0_0_state_1, e0_0_state_0});
  wire rom_160 = lut4(16'hCCCC, {1'b0, 1'b0, e0_0_state_1, e0_0_state_0});
  wire rom_161 = lut4(16'hAAAA, {1'b0, 1'b0, e0_0_state_1, e0_0_state_0});
  wire rom_162 = lut4(16'hCCCC, {1'b0, 1'b0, e0_0_state_1, e0_0_state_0});
  wire rom_163 = lut4(16'hFFFF, {1'b0, 1'b0, e0_0_state_1, e0_0_state_0});
  wire xnor_164 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e0_0_state_0});
  wire xnor_165 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e0_0_state_1});
  wire nand_167 = lut4(16'h7777, {1'b0, 1'b0, e0_0_s_valid, e0_0_a_valid});
  wire xor3_169 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, e0_0_state_0});
  wire maj_170 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, e0_0_state_0});
  wire [31:0] pe3_187 = (e0_0_a_x * e0_0_a_w);
  wire not_188 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, e0_0_s_valid});
  wire acc_ready_190 = lut4(16'hF7F7, {1'b0, y_ready, e0_0_r_valid, e0_0_o_last});
  wire [31:0] pe1_206 = (e0_0_acc + e0_0_o_p);
  wire [31:0] k_209 = 32'h00000000;
  wire rom_232 = lut4(16'hAAAA, {1'b0, 1'b0, e0_1_state_1, e0_1_state_0});
  wire rom_233 = lut4(16'hCCCC, {1'b0, 1'b0, e0_1_state_1, e0_1_state_0});
  wire rom_234 = lut4(16'hAAAA, {1'b0, 1'b0, e0_1_state_1, e0_1_state_0});
  wire rom_235 = lut4(16'hCCCC, {1'b0, 1'b0, e0_1_state_1, e0_1_state_0});
  wire rom_236 = lut4(16'hFFFF, {1'b0, 1'b0, e0_1_state_1, e0_1_state_0});
  wire xnor_237 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e0_1_state_0});
  wire xnor_238 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e0_1_state_1});
  wire nand_240 = lut4(16'h7777, {1'b0, 1'b0, e0_1_s_valid, e0_1_a_valid});
  wire xor3_242 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, e0_1_state_0});
  wire maj_243 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, e0_1_state_0});
  wire [31:0] pe3_260 = (e0_1_a_x * e0_1_a_w);
  wire not_261 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, e0_1_s_valid});
  wire acc_ready_263 = lut4(16'hF7F7, {1'b0, y_ready, e0_1_r_valid, e0_1_o_last});
  wire [31:0] pe1_279 = (e0_1_acc + e0_1_o_p);
  wire [31:0] k_282 = 32'h00000000;
  wire [31:0] pe1_287 = (e0_0_res + e0_1_res);
  wire rom_306 = lut4(16'hAAAA, {1'b0, 1'b0, e1_0_state_1, e1_0_state_0});
  wire rom_307 = lut4(16'hCCCC, {1'b0, 1'b0, e1_0_state_1, e1_0_state_0});
  wire rom_308 = lut4(16'hAAAA, {1'b0, 1'b0, e1_0_state_1, e1_0_state_0});
  wire rom_309 = lut4(16'hCCCC, {1'b0, 1'b0, e1_0_state_1, e1_0_state_0});
  wire rom_310 = lut4(16'hFFFF, {1'b0, 1'b0, e1_0_state_1, e1_0_state_0});
  wire xnor_311 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e1_0_state_0});
  wire xnor_312 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e1_0_state_1});
  wire nand_314 = lut4(16'h7777, {1'b0, 1'b0, e1_0_s_valid, e1_0_a_valid});
  wire xor3_316 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, e1_0_state_0});
  wire maj_317 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, e1_0_state_0});
  wire [31:0] pe3_334 = (e1_0_a_x * e1_0_a_w);
  wire not_335 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, e1_0_s_valid});
  wire acc_ready_337 = lut4(16'hF7F7, {1'b0, y_ready, e1_0_r_valid, e1_0_o_last});
  wire [31:0] pe1_353 = (e1_0_acc + e1_0_o_p);
  wire [31:0] k_356 = 32'h00000000;
  wire rom_379 = lut4(16'hAAAA, {1'b0, 1'b0, e1_1_state_1, e1_1_state_0});
  wire rom_380 = lut4(16'hCCCC, {1'b0, 1'b0, e1_1_state_1, e1_1_state_0});
  wire rom_381 = lut4(16'hAAAA, {1'b0, 1'b0, e1_1_state_1, e1_1_state_0});
  wire rom_382 = lut4(16'hCCCC, {1'b0, 1'b0, e1_1_state_1, e1_1_state_0});
  wire rom_383 = lut4(16'hFFFF, {1'b0, 1'b0, e1_1_state_1, e1_1_state_0});
  wire xnor_384 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e1_1_state_0});
  wire xnor_385 = lut4(16'h9999, {1'b0, 1'b0, 1'b1, e1_1_state_1});
  wire nand_387 = lut4(16'h7777, {1'b0, 1'b0, e1_1_s_valid, e1_1_a_valid});
  wire xor3_389 = lut4(16'h9696, {1'b0, 1'b0, 1'b1, e1_1_state_0});
  wire maj_390 = lut4(16'hE8E8, {1'b0, 1'b0, 1'b1, e1_1_state_0});
  wire [31:0] pe3_407 = (e1_1_a_x * e1_1_a_w);
  wire not_408 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, e1_1_s_valid});
  wire acc_ready_410 = lut4(16'hF7F7, {1'b0, y_ready, e1_1_r_valid, e1_1_o_last});
  wire [31:0] pe1_426 = (e1_1_acc + e1_1_o_p);
  wire [31:0] k_429 = 32'h00000000;
  wire [31:0] pe1_434 = (e1_0_res + e1_1_res);
  wire not_435 = lut4(16'h5555, {1'b0, 1'b0, 1'b0, pend});

  // level 1
  wire and_36 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_19});
  wire and_37 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_21});
  wire and_38 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_22});
  wire and_39 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_23});
  wire and_40 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_24});
  wire and_41 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_25});
  wire and_42 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_26});
  wire and_43 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_27});
  wire and_44 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_28});
  wire and_45 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_29});
  wire and_46 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_30});
  wire and_47 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_31});
  wire and_48 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_32});
  wire and_49 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_33});
  wire and_50 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_34});
  wire and_51 = lut4(16'h8888, {1'b0, 1'b0, dec_hi_20, dec_lo_35});
  wire and4_102 = lut4(16'h8000, {1'b1, 1'b1, xnor_101, xnor_100});
  wire and4_106 = lut4(16'h8000, {1'b1, 1'b1, xnor_105, xnor_104});
  wire and4_110 = lut4(16'h8000, {1'b1, 1'b1, xnor_109, xnor_108});
  wire and4_114 = lut4(16'h8000, {1'b1, 1'b1, xnor_113, xnor_112});
  wire and4_166 = lut4(16'h8000, {1'b1, 1'b1, xnor_165, xnor_164});
  wire and_168 = lut4(16'h8888, {1'b0, 1'b0, nand_167, pend});
  wire xor3_171 = lut4(16'h9696, {1'b0, maj_170, 1'b0, e0_0_state_1});
  wire maj_172 = lut4(16'hE8E8, {1'b0, maj_170, 1'b0, e0_0_state_1});
  wire [31:0] sel_176 = (rom_159 ? xa0_1 : xa0_0);
  wire [31:0] sel_177 = (rom_159 ? xa0_3 : xa0_2);
  wire [31:0] sel_180 = (rom_161 ? wt1 : wt0);
  wire [31:0] sel_181 = (rom_161 ? wt3 : wt2);
  wire and_189 = lut4(16'h8888, {1'b0, 1'b0, not_188, e0_0_a_valid});
  wire and_191 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_190, e0_0_o_valid});
  wire [31:0] sel_207 = (e0_0_o_mac ? pe1_206 : e0_0_acc);
  wire and4_239 = lut4(16'h8000, {1'b1, 1'b1, xnor_238, xnor_237});
  wire and_241 = lut4(16'h8888, {1'b0, 1'b0, nand_240, pend});
  wire xor3_244 = lut4(16'h9696, {1'b0, maj_243, 1'b0, e0_1_state_1});
  wire maj_245 = lut4(16'hE8E8, {1'b0, maj_243, 1'b0, e0_1_state_1});
  wire [31:0] sel_249 = (rom_232 ? xa1_1 : xa1_0);
  wire [31:0] sel_250 = (rom_232 ? xa1_3 : xa1_2);
  wire [31:0] sel_253 = (rom_234 ? wt5 : wt4);
  wire [31:0] sel_254 = (rom_234 ? wt7 : wt6);
  wire and_262 = lut4(16'h8888, {1'b0, 1'b0, not_261, e0_1_a_valid});
  wire and_264 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_263, e0_1_o_valid});
  wire [31:0] sel_280 = (e0_1_o_mac ? pe1_279 : e0_1_acc);
  wire and4_313 = lut4(16'h8000, {1'b1, 1'b1, xnor_312, xnor_311});
  wire and_315 = lut4(16'h8888, {1'b0, 1'b0, nand_314, pend});
  wire xor3_318 = lut4(16'h9696, {1'b0, maj_317, 1'b0, e1_0_state_1});
  wire maj_319 = lut4(16'hE8E8, {1'b0, maj_317, 1'b0, e1_0_state_1});
  wire [31:0] sel_323 = (rom_306 ? xa0_1 : xa0_0);
  wire [31:0] sel_324 = (rom_306 ? xa0_3 : xa0_2);
  wire [31:0] sel_327 = (rom_308 ? wt9 : wt8);
  wire [31:0] sel_328 = (rom_308 ? wt11 : wt10);
  wire and_336 = lut4(16'h8888, {1'b0, 1'b0, not_335, e1_0_a_valid});
  wire and_338 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_337, e1_0_o_valid});
  wire [31:0] sel_354 = (e1_0_o_mac ? pe1_353 : e1_0_acc);
  wire and4_386 = lut4(16'h8000, {1'b1, 1'b1, xnor_385, xnor_384});
  wire and_388 = lut4(16'h8888, {1'b0, 1'b0, nand_387, pend});
  wire xor3_391 = lut4(16'h9696, {1'b0, maj_390, 1'b0, e1_1_state_1});
  wire maj_392 = lut4(16'hE8E8, {1'b0, maj_390, 1'b0, e1_1_state_1});
  wire [31:0] sel_396 = (rom_379 ? xa1_1 : xa1_0);
  wire [31:0] sel_397 = (rom_379 ? xa1_3 : xa1_2);
  wire [31:0] sel_400 = (rom_381 ? wt13 : wt12);
  wire [31:0] sel_401 = (rom_381 ? wt15 : wt14);
  wire and_409 = lut4(16'h8888, {1'b0, 1'b0, not_408, e1_1_a_valid});
  wire and_411 = lut4(16'h8888, {1'b0, 1'b0, acc_ready_410, e1_1_o_valid});
  wire [31:0] sel_427 = (e1_1_o_mac ? pe1_426 : e1_1_acc);

  // level 2
  wire and_53 = lut4(16'h8888, {1'b0, 1'b0, and_36, w_we});
  wire and_56 = lut4(16'h8888, {1'b0, 1'b0, and_37, w_we});
  wire and_59 = lut4(16'h8888, {1'b0, 1'b0, and_38, w_we});
  wire and_62 = lut4(16'h8888, {1'b0, 1'b0, and_39, w_we});
  wire and_65 = lut4(16'h8888, {1'b0, 1'b0, and_40, w_we});
  wire and_68 = lut4(16'h8888, {1'b0, 1'b0, and_41, w_we});
  wire and_71 = lut4(16'h8888, {1'b0, 1'b0, and_42, w_we});
  wire and_74 = lut4(16'h8888, {1'b0, 1'b0, and_43, w_we});
  wire and_77 = lut4(16'h8888, {1'b0, 1'b0, and_44, w_we});
  wire and_80 = lut4(16'h8888, {1'b0, 1'b0, and_45, w_we});
  wire and_83 = lut4(16'h8888, {1'b0, 1'b0, and_46, w_we});
  wire and_86 = lut4(16'h8888, {1'b0, 1'b0, and_47, w_we});
  wire and_89 = lut4(16'h8888, {1'b0, 1'b0, and_48, w_we});
  wire and_92 = lut4(16'h8888, {1'b0, 1'b0, and_49, w_we});
  wire and_95 = lut4(16'h8888, {1'b0, 1'b0, and_50, w_we});
  wire and_98 = lut4(16'h8888, {1'b0, 1'b0, and_51, w_we});
  wire and_103 = lut4(16'h8888, {1'b0, 1'b0, and4_102, x_we});
  wire and_107 = lut4(16'h8888, {1'b0, 1'b0, and4_106, x_we});
  wire and_111 = lut4(16'h8888, {1'b0, 1'b0, and4_110, x_we});
  wire and_115 = lut4(16'h8888, {1'b0, 1'b0, and4_114, x_we});
  wire mux_173 = lut4(16'hE4E4, {1'b0, xor3_169, e0_0_state_0, and_168});
  wire mux_174 = lut4(16'hE4E4, {1'b0, xor3_171, e0_0_state_1, and_168});
  wire and_175 = lut4(16'h8888, {1'b0, 1'b0, and4_166, and_168});
  wire [31:0] sel_178 = (rom_160 ? sel_177 : sel_176);
  wire [31:0] sel_182 = (rom_162 ? sel_181 : sel_180);
  wire mux_184 = lut4(16'hE4E4, {1'b0, rom_163, e0_0_a_mac, and_168});
  wire mux_185 = lut4(16'hE4E4, {1'b0, and4_166, e0_0_a_last, and_168});
  wire a_valid_next_186 = lut4(16'hEAEA, {1'b0, e0_0_s_valid, e0_0_a_valid, and_168});
  wire and_192 = lut4(16'h8888, {1'b0, 1'b0, e0_0_s_valid, and_191});
  wire o_take_193 = lut4(16'hA2A2, {1'b0, and_191, e0_0_o_valid, and_189});
  wire s_take_194 = lut4(16'h0808, {1'b0, and_191, e0_0_o_valid, and_189});
  wire and_208 = lut4(16'h8888, {1'b0, 1'b0, e0_0_o_last, and_191});
  wire [31:0] sel_210 = (e0_0_o_last ? k_209 : sel_207);
  wire mux_246 = lut4(16'hE4E4, {1'b0, xor3_242, e0_1_state_0, and_241});
  wire mux_247 = lut4(16'hE4E4, {1'b0, xor3_244, e0_1_state_1, and_241});
  wire and_248 = lut4(16'h8888, {1'b0, 1'b0, and4_239, and_241});
  wire [31:0] sel_251 = (rom_233 ? sel_250 : sel_249);
  wire [31:0] sel_255 = (rom_235 ? sel_254 : sel_253);
  wire mux_257 = lut4(16'hE4E4, {1'b0, rom_236, e0_1_a_mac, and_241});
  wire mux_258 = lut4(16'hE4E4, {1'b0, and4_239, e0_1_a_last, and_241});
  wire a_valid_next_259 = lut4(16'hEAEA, {1'b0, e0_1_s_valid, e0_1_a_valid, and_241});
  wire and_265 = lut4(16'h8888, {1'b0, 1'b0, e0_1_s_valid, and_264});
  wire o_take_266 = lut4(16'hA2A2, {1'b0, and_264, e0_1_o_valid, and_262});
  wire s_take_267 = lut4(16'h0808, {1'b0, and_264, e0_1_o_valid, and_262});
  wire and_281 = lut4(16'h8888, {1'b0, 1'b0, e0_1_o_last, and_264});
  wire [31:0] sel_283 = (e0_1_o_last ? k_282 : sel_280);
  wire mux_320 = lut4(16'hE4E4, {1'b0, xor3_316, e1_0_state_0, and_315});
  wire mux_321 = lut4(16'hE4E4, {1'b0, xor3_318, e1_0_state_1, and_315});
  wire and_322 = lut4(16'h8888, {1'b0, 1'b0, and4_313, and_315});
  wire [31:0] sel_325 = (rom_307 ? sel_324 : sel_323);
  wire [31:0] sel_329 = (rom_309 ? sel_328 : sel_327);
  wire mux_331 = lut4(16'hE4E4, {1'b0, rom_310, e1_0_a_mac, and_315});
  wire mux_332 = lut4(16'hE4E4, {1'b0, and4_313, e1_0_a_last, and_315});
  wire a_valid_next_333 = lut4(16'hEAEA, {1'b0, e1_0_s_valid, e1_0_a_valid, and_315});
  wire and_339 = lut4(16'h8888, {1'b0, 1'b0, e1_0_s_valid, and_338});
  wire o_take_340 = lut4(16'hA2A2, {1'b0, and_338, e1_0_o_valid, and_336});
  wire s_take_341 = lut4(16'h0808, {1'b0, and_338, e1_0_o_valid, and_336});
  wire and_355 = lut4(16'h8888, {1'b0, 1'b0, e1_0_o_last, and_338});
  wire [31:0] sel_357 = (e1_0_o_last ? k_356 : sel_354);
  wire mux_393 = lut4(16'hE4E4, {1'b0, xor3_389, e1_1_state_0, and_388});
  wire mux_394 = lut4(16'hE4E4, {1'b0, xor3_391, e1_1_state_1, and_388});
  wire and_395 = lut4(16'h8888, {1'b0, 1'b0, and4_386, and_388});
  wire [31:0] sel_398 = (rom_380 ? sel_397 : sel_396);
  wire [31:0] sel_402 = (rom_382 ? sel_401 : sel_400);
  wire mux_404 = lut4(16'hE4E4, {1'b0, rom_383, e1_1_a_mac, and_388});
  wire mux_405 = lut4(16'hE4E4, {1'b0, and4_386, e1_1_a_last, and_388});
  wire a_valid_next_406 = lut4(16'hEAEA, {1'b0, e1_1_s_valid, e1_1_a_valid, and_388});
  wire and_412 = lut4(16'h8888, {1'b0, 1'b0, e1_1_s_valid, and_411});
  wire o_take_413 = lut4(16'hA2A2, {1'b0, and_411, e1_1_o_valid, and_409});
  wire s_take_414 = lut4(16'h0808, {1'b0, and_411, e1_1_o_valid, and_409});
  wire and_428 = lut4(16'h8888, {1'b0, 1'b0, e1_1_o_last, and_411});
  wire [31:0] sel_430 = (e1_1_o_last ? k_429 : sel_427);

  // level 3
  wire [31:0] sel_54 = (and_53 ? w_data : wt0);
  wire [31:0] sel_57 = (and_56 ? w_data : wt1);
  wire [31:0] sel_60 = (and_59 ? w_data : wt2);
  wire [31:0] sel_63 = (and_62 ? w_data : wt3);
  wire [31:0] sel_66 = (and_65 ? w_data : wt4);
  wire [31:0] sel_69 = (and_68 ? w_data : wt5);
  wire [31:0] sel_72 = (and_71 ? w_data : wt6);
  wire [31:0] sel_75 = (and_74 ? w_data : wt7);
  wire [31:0] sel_78 = (and_77 ? w_data : wt8);
  wire [31:0] sel_81 = (and_80 ? w_data : wt9);
  wire [31:0] sel_84 = (and_83 ? w_data : wt10);
  wire [31:0] sel_87 = (and_86 ? w_data : wt11);
  wire [31:0] sel_90 = (and_89 ? w_data : wt12);
  wire [31:0] sel_93 = (and_92 ? w_data : wt13);
  wire [31:0] sel_96 = (and_95 ? w_data : wt14);
  wire [31:0] sel_99 = (and_98 ? w_data : wt15);
  wire [31:0] sel_119 = (and_103 ? x0 : xs0_0);
  wire [31:0] sel_122 = (and_107 ? x0 : xs0_1);
  wire [31:0] sel_125 = (and_111 ? x0 : xs0_2);
  wire [31:0] sel_128 = (and_115 ? x0 : xs0_3);
  wire [31:0] sel_131 = (and_103 ? x1 : xs1_0);
  wire [31:0] sel_134 = (and_107 ? x1 : xs1_1);
  wire [31:0] sel_137 = (and_111 ? x1 : xs1_2);
  wire [31:0] sel_140 = (and_115 ? x1 : xs1_3);
  wire [31:0] sel_179 = (and_168 ? sel_178 : e0_0_a_x);
  wire [31:0] sel_183 = (and_168 ? sel_182 : e0_0_a_w);
  wire o_valid_next_195 = lut4(16'hEEFE, {and_191, e0_0_o_valid, o_take_193, and_192});
  wire [31:0] sel_196 = (o_take_193 ? pe3_187 : e0_0_o_p);
  wire mux_198 = lut4(16'hE4E4, {1'b0, e0_0_a_mac, e0_0_o_mac, o_take_193});
  wire mux_200 = lut4(16'hE4E4, {1'b0, e0_0_a_last, e0_0_o_last, o_take_193});
  wire s_valid_next_202 = lut4(16'hAEAE, {1'b0, and_192, e0_0_s_valid, s_take_194});
  wire [31:0] sel_203 = (s_take_194 ? pe3_187 : e0_0_s_p);
  wire mux_204 = lut4(16'hE4E4, {1'b0, e0_0_a_mac, e0_0_s_mac, s_take_194});
  wire mux_205 = lut4(16'hE4E4, {1'b0, e0_0_a_last, e0_0_s_last, s_take_194});
  wire [31:0] sel_211 = (and_191 ? sel_210 : e0_0_acc);
  wire [31:0] sel_212 = (and_208 ? sel_207 : e0_0_res);
  wire r_valid_next_213 = lut4(16'hAEAE, {1'b0, y_ready, e0_0_r_valid, and_208});
  wire [31:0] sel_252 = (and_241 ? sel_251 : e0_1_a_x);
  wire [31:0] sel_256 = (and_241 ? sel_255 : e0_1_a_w);
  wire o_valid_next_268 = lut4(16'hEEFE, {and_264, e0_1_o_valid, o_take_266, and_265});
  wire [31:0] sel_269 = (o_take_266 ? pe3_260 : e0_1_o_p);
  wire mux_271 = lut4(16'hE4E4, {1'b0, e0_1_a_mac, e0_1_o_mac, o_take_266});
  wire mux_273 = lut4(16'hE4E4, {1'b0, e0_1_a_last, e0_1_o_last, o_take_266});
  wire s_valid_next_275 = lut4(16'hAEAE, {1'b0, and_265, e0_1_s_valid, s_take_267});
  wire [31:0] sel_276 = (s_take_267 ? pe3_260 : e0_1_s_p);
  wire mux_277 = lut4(16'hE4E4, {1'b0, e0_1_a_mac, e0_1_s_mac, s_take_267});
  wire mux_278 = lut4(16'hE4E4, {1'b0, e0_1_a_last, e0_1_s_last, s_take_267});
  wire [31:0] sel_284 = (and_264 ? sel_283 : e0_1_acc);
  wire [31:0] sel_285 = (and_281 ? sel_280 : e0_1_res);
  wire r_valid_next_286 = lut4(16'hAEAE, {1'b0, y_ready, e0_1_r_valid, and_281});
  wire [31:0] sel_326 = (and_315 ? sel_325 : e1_0_a_x);
  wire [31:0] sel_330 = (and_315 ? sel_329 : e1_0_a_w);
  wire o_valid_next_342 = lut4(16'hEEFE, {and_338, e1_0_o_valid, o_take_340, and_339});
  wire [31:0] sel_343 = (o_take_340 ? pe3_334 : e1_0_o_p);
  wire mux_345 = lut4(16'hE4E4, {1'b0, e1_0_a_mac, e1_0_o_mac, o_take_340});
  wire mux_347 = lut4(16'hE4E4, {1'b0, e1_0_a_last, e1_0_o_last, o_take_340});
  wire s_valid_next_349 = lut4(16'hAEAE, {1'b0, and_339, e1_0_s_valid, s_take_341});
  wire [31:0] sel_350 = (s_take_341 ? pe3_334 : e1_0_s_p);
  wire mux_351 = lut4(16'hE4E4, {1'b0, e1_0_a_mac, e1_0_s_mac, s_take_341});
  wire mux_352 = lut4(16'hE4E4, {1'b0, e1_0_a_last, e1_0_s_last, s_take_341});
  wire [31:0] sel_358 = (and_338 ? sel_357 : e1_0_acc);
  wire [31:0] sel_359 = (and_355 ? sel_354 : e1_0_res);
  wire r_valid_next_360 = lut4(16'hAEAE, {1'b0, y_ready, e1_0_r_valid, and_355});
  wire [31:0] sel_399 = (and_388 ? sel_398 : e1_1_a_x);
  wire [31:0] sel_403 = (and_388 ? sel_402 : e1_1_a_w);
  wire o_valid_next_415 = lut4(16'hEEFE, {and_411, e1_1_o_valid, o_take_413, and_412});
  wire [31:0] sel_416 = (o_take_413 ? pe3_407 : e1_1_o_p);
  wire mux_418 = lut4(16'hE4E4, {1'b0, e1_1_a_mac, e1_1_o_mac, o_take_413});
  wire mux_420 = lut4(16'hE4E4, {1'b0, e1_1_a_last, e1_1_o_last, o_take_413});
  wire s_valid_next_422 = lut4(16'hAEAE, {1'b0, and_412, e1_1_s_valid, s_take_414});
  wire [31:0] sel_423 = (s_take_414 ? pe3_407 : e1_1_s_p);
  wire mux_424 = lut4(16'hE4E4, {1'b0, e1_1_a_mac, e1_1_s_mac, s_take_414});
  wire mux_425 = lut4(16'hE4E4, {1'b0, e1_1_a_last, e1_1_s_last, s_take_414});
  wire [31:0] sel_431 = (and_411 ? sel_430 : e1_1_acc);
  wire [31:0] sel_432 = (and_428 ? sel_427 : e1_1_res);
  wire r_valid_next_433 = lut4(16'hAEAE, {1'b0, y_ready, e1_1_r_valid, and_428});
  wire or_436 = lut4(16'hEEEE, {1'b0, 1'b0, and_175, not_435});

  // level 4
  wire [31:0] sel_197 = (and_192 ? e0_0_s_p : sel_196);
  wire mux_199 = lut4(16'hE4E4, {1'b0, e0_0_s_mac, mux_198, and_192});
  wire mux_201 = lut4(16'hE4E4, {1'b0, e0_0_s_last, mux_200, and_192});
  wire [31:0] sel_270 = (and_265 ? e0_1_s_p : sel_269);
  wire mux_272 = lut4(16'hE4E4, {1'b0, e0_1_s_mac, mux_271, and_265});
  wire mux_274 = lut4(16'hE4E4, {1'b0, e0_1_s_last, mux_273, and_265});
  wire [31:0] sel_344 = (and_339 ? e1_0_s_p : sel_343);
  wire mux_346 = lut4(16'hE4E4, {1'b0, e1_0_s_mac, mux_345, and_339});
  wire mux_348 = lut4(16'hE4E4, {1'b0, e1_0_s_last, mux_347, and_339});
  wire [31:0] sel_417 = (and_412 ? e1_1_s_p : sel_416);
  wire mux_419 = lut4(16'hE4E4, {1'b0, e1_1_s_mac, mux_418, and_412});
  wire mux_421 = lut4(16'hE4E4, {1'b0, e1_1_s_last, mux_420, and_412});
  wire and_437 = lut4(16'h8888, {1'b0, 1'b0, or_436, x_go});

  // level 5
  wire [31:0] sel_438 = (and_437 ? sel_119 : xa0_0);
  wire [31:0] sel_439 = (and_437 ? sel_122 : xa0_1);
  wire [31:0] sel_440 = (and_437 ? sel_125 : xa0_2);
  wire [31:0] sel_441 = (and_437 ? sel_128 : xa0_3);
  wire [31:0] sel_442 = (and_437 ? sel_131 : xa1_0);
  wire [31:0] sel_443 = (and_437 ? sel_134 : xa1_1);
  wire [31:0] sel_444 = (and_437 ? sel_137 : xa1_2);
  wire [31:0] sel_445 = (and_437 ? sel_140 : xa1_3);
  wire pend_next_446 = lut4(16'hAEAE, {1'b0, and_175, pend, and_437});

  always @(posedge clk) begin
    if (rst) begin
      wt0 <= 32'h00000000;
      wt1 <= 32'h00000000;
      wt2 <= 32'h00000000;
      wt3 <= 32'h00000000;
      wt4 <= 32'h00000000;
      wt5 <= 32'h00000000;
      wt6 <= 32'h00000000;
      wt7 <= 32'h00000000;
      wt8 <= 32'h00000000;
      wt9 <= 32'h00000000;
      wt10 <= 32'h00000000;
      wt11 <= 32'h00000000;
      wt12 <= 32'h00000000;
      wt13 <= 32'h00000000;
      wt14 <= 32'h00000000;
      wt15 <= 32'h00000000;
      pend <= 1'h0;
      xs0_0 <= 32'h00000000;
      xa0_0 <= 32'h00000000;
      xs0_1 <= 32'h00000000;
      xa0_1 <= 32'h00000000;
      xs0_2 <= 32'h00000000;
      xa0_2 <= 32'h00000000;
      xs0_3 <= 32'h00000000;
      xa0_3 <= 32'h00000000;
      xs1_0 <= 32'h00000000;
      xa1_0 <= 32'h00000000;
      xs1_1 <= 32'h00000000;
      xa1_1 <= 32'h00000000;
      xs1_2 <= 32'h00000000;
      xa1_2 <= 32'h00000000;
      xs1_3 <= 32'h00000000;
      xa1_3 <= 32'h00000000;
      e0_0_state_0 <= 1'h0;
      e0_0_state_1 <= 1'h0;
      e0_0_o_valid <= 1'h0;
      e0_0_o_mac <= 1'h0;
      e0_0_o_last <= 1'h0;
      e0_0_s_valid <= 1'h0;
      e0_0_s_mac <= 1'h0;
      e0_0_s_last <= 1'h0;
      e0_0_r_valid <= 1'h0;
      e0_0_o_p <= 32'h00000000;
      e0_0_s_p <= 32'h00000000;
      e0_0_acc <= 32'h00000000;
      e0_0_res <= 32'h00000000;
      e0_0_a_valid <= 1'h0;
      e0_0_a_mac <= 1'h0;
      e0_0_a_last <= 1'h0;
      e0_0_a_x <= 32'h00000000;
      e0_0_a_w <= 32'h00000000;
      e0_1_state_0 <= 1'h0;
      e0_1_state_1 <= 1'h0;
      e0_1_o_valid <= 1'h0;
      e0_1_o_mac <= 1'h0;
      e0_1_o_last <= 1'h0;
      e0_1_s_valid <= 1'h0;
      e0_1_s_mac <= 1'h0;
      e0_1_s_last <= 1'h0;
      e0_1_r_valid <= 1'h0;
      e0_1_o_p <= 32'h00000000;
      e0_1_s_p <= 32'h00000000;
      e0_1_acc <= 32'h00000000;
      e0_1_res <= 32'h00000000;
      e0_1_a_valid <= 1'h0;
      e0_1_a_mac <= 1'h0;
      e0_1_a_last <= 1'h0;
      e0_1_a_x <= 32'h00000000;
      e0_1_a_w <= 32'h00000000;
      e1_0_state_0 <= 1'h0;
      e1_0_state_1 <= 1'h0;
      e1_0_o_valid <= 1'h0;
      e1_0_o_mac <= 1'h0;
      e1_0_o_last <= 1'h0;
      e1_0_s_valid <= 1'h0;
      e1_0_s_mac <= 1'h0;
      e1_0_s_last <= 1'h0;
      e1_0_r_valid <= 1'h0;
      e1_0_o_p <= 32'h00000000;
      e1_0_s_p <= 32'h00000000;
      e1_0_acc <= 32'h00000000;
      e1_0_res <= 32'h00000000;
      e1_0_a_valid <= 1'h0;
      e1_0_a_mac <= 1'h0;
      e1_0_a_last <= 1'h0;
      e1_0_a_x <= 32'h00000000;
      e1_0_a_w <= 32'h00000000;
      e1_1_state_0 <= 1'h0;
      e1_1_state_1 <= 1'h0;
      e1_1_o_valid <= 1'h0;
      e1_1_o_mac <= 1'h0;
      e1_1_o_last <= 1'h0;
      e1_1_s_valid <= 1'h0;
      e1_1_s_mac <= 1'h0;
      e1_1_s_last <= 1'h0;
      e1_1_r_valid <= 1'h0;
      e1_1_o_p <= 32'h00000000;
      e1_1_s_p <= 32'h00000000;
      e1_1_acc <= 32'h00000000;
      e1_1_res <= 32'h00000000;
      e1_1_a_valid <= 1'h0;
      e1_1_a_mac <= 1'h0;
      e1_1_a_last <= 1'h0;
      e1_1_a_x <= 32'h00000000;
      e1_1_a_w <= 32'h00000000;
    end else begin
      wt0 <= sel_54;
      wt1 <= sel_57;
      wt2 <= sel_60;
      wt3 <= sel_63;
      wt4 <= sel_66;
      wt5 <= sel_69;
      wt6 <= sel_72;
      wt7 <= sel_75;
      wt8 <= sel_78;
      wt9 <= sel_81;
      wt10 <= sel_84;
      wt11 <= sel_87;
      wt12 <= sel_90;
      wt13 <= sel_93;
      wt14 <= sel_96;
      wt15 <= sel_99;
      pend <= pend_next_446;
      xs0_0 <= sel_119;
      xa0_0 <= sel_438;
      xs0_1 <= sel_122;
      xa0_1 <= sel_439;
      xs0_2 <= sel_125;
      xa0_2 <= sel_440;
      xs0_3 <= sel_128;
      xa0_3 <= sel_441;
      xs1_0 <= sel_131;
      xa1_0 <= sel_442;
      xs1_1 <= sel_134;
      xa1_1 <= sel_443;
      xs1_2 <= sel_137;
      xa1_2 <= sel_444;
      xs1_3 <= sel_140;
      xa1_3 <= sel_445;
      e0_0_state_0 <= mux_173;
      e0_0_state_1 <= mux_174;
      e0_0_o_valid <= o_valid_next_195;
      e0_0_o_mac <= mux_199;
      e0_0_o_last <= mux_201;
      e0_0_s_valid <= s_valid_next_202;
      e0_0_s_mac <= mux_204;
      e0_0_s_last <= mux_205;
      e0_0_r_valid <= r_valid_next_213;
      e0_0_o_p <= sel_197;
      e0_0_s_p <= sel_203;
      e0_0_acc <= sel_211;
      e0_0_res <= sel_212;
      e0_0_a_valid <= a_valid_next_186;
      e0_0_a_mac <= mux_184;
      e0_0_a_last <= mux_185;
      e0_0_a_x <= sel_179;
      e0_0_a_w <= sel_183;
      e0_1_state_0 <= mux_246;
      e0_1_state_1 <= mux_247;
      e0_1_o_valid <= o_valid_next_268;
      e0_1_o_mac <= mux_272;
      e0_1_o_last <= mux_274;
      e0_1_s_valid <= s_valid_next_275;
      e0_1_s_mac <= mux_277;
      e0_1_s_last <= mux_278;
      e0_1_r_valid <= r_valid_next_286;
      e0_1_o_p <= sel_270;
      e0_1_s_p <= sel_276;
      e0_1_acc <= sel_284;
      e0_1_res <= sel_285;
      e0_1_a_valid <= a_valid_next_259;
      e0_1_a_mac <= mux_257;
      e0_1_a_last <= mux_258;
      e0_1_a_x <= sel_252;
      e0_1_a_w <= sel_256;
      e1_0_state_0 <= mux_320;
      e1_0_state_1 <= mux_321;
      e1_0_o_valid <= o_valid_next_342;
      e1_0_o_mac <= mux_346;
      e1_0_o_last <= mux_348;
      e1_0_s_valid <= s_valid_next_349;
      e1_0_s_mac <= mux_351;
      e1_0_s_last <= mux_352;
      e1_0_r_valid <= r_valid_next_360;
      e1_0_o_p <= sel_344;
      e1_0_s_p <= sel_350;
      e1_0_acc <= sel_358;
      e1_0_res <= sel_359;
      e1_0_a_valid <= a_valid_next_333;
      e1_0_a_mac <= mux_331;
      e1_0_a_last <= mux_332;
      e1_0_a_x <= sel_326;
      e1_0_a_w <= sel_330;
      e1_1_state_0 <= mux_393;
      e1_1_state_1 <= mux_394;
      e1_1_o_valid <= o_valid_next_415;
      e1_1_o_mac <= mux_419;
      e1_1_o_last <= mux_421;
      e1_1_s_valid <= s_valid_next_422;
      e1_1_s_mac <= mux_424;
      e1_1_s_last <= mux_425;
      e1_1_r_valid <= r_valid_next_433;
      e1_1_o_p <= sel_417;
      e1_1_s_p <= sel_423;
      e1_1_acc <= sel_431;
      e1_1_res <= sel_432;
      e1_1_a_valid <= a_valid_next_406;
      e1_1_a_mac <= mux_404;
      e1_1_a_last <= mux_405;
      e1_1_a_x <= sel_399;
      e1_1_a_w <= sel_403;
    end
  end

  // outputs
  assign x_ready = or_436;
  assign y0 = pe1_287;
  assign y1 = pe1_434;
  assign y_valid = e0_0_r_valid;
endmodule
