-- jev_tile_2x2_tb.vhd -- self-checking testbench generated by the WASMApollo EDA; the expected
-- values are the fabric's golden model (RefSim). Run: ghdl -a jev_tile_2x2.vhd jev_tile_2x2_tb.vhd && ghdl -e jev_tile_2x2_tb && ghdl -r jev_tile_2x2_tb

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_tile_2x2_tb is
end entity jev_tile_2x2_tb;

architecture sim of jev_tile_2x2_tb is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal finished : boolean := false;
  signal w_we : std_logic := '0';
  signal w_addr : std_logic_vector(7 downto 0) := (others => '0');
  signal w_data : unsigned(31 downto 0) := (others => '0');
  signal x_we : std_logic := '0';
  signal x_k : std_logic_vector(1 downto 0) := (others => '0');
  signal x0 : unsigned(31 downto 0) := (others => '0');
  signal x1 : unsigned(31 downto 0) := (others => '0');
  signal x_go : std_logic := '0';
  signal y_ready : std_logic := '0';
  signal x_ready : std_logic;
  signal y0 : unsigned(31 downto 0);
  signal y1 : unsigned(31 downto 0);
  signal y_valid : std_logic;
begin
  dut : entity work.jev_tile_2x2 port map (clk => clk, rst => rst, w_we => w_we, w_addr => w_addr, w_data => w_data, x_we => x_we, x_k => x_k, x0 => x0, x1 => x1, x_go => x_go, y_ready => y_ready, x_ready => x_ready, y0 => y0, y1 => y1, y_valid => y_valid);
  clk <= not clk after 5 ns when not finished else '0';

  check : process
    variable errors : natural := 0;
    procedure tick is
    begin
      wait until rising_edge(clk);
      wait for 1 ns;
    end procedure;
  begin
    -- vector 0
    w_we <= '0';
    w_addr <= "00001111";
    w_data <= x"00007B06";
    x_we <= '0';
    x_k <= "10";
    x0 <= x"00003AB5";
    x1 <= x"000090B6";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 0: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 0: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 0: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 0: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 1
    w_we <= '1';
    w_addr <= "00001101";
    w_data <= x"000099B2";
    x_we <= '0';
    x_k <= "00";
    x0 <= x"0000BC3B";
    x1 <= x"00002B5E";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 1: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 1: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 1: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 1: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 2
    w_we <= '0';
    w_addr <= "00000100";
    w_data <= x"0000B6EC";
    x_we <= '1';
    x_k <= "01";
    x0 <= x"0000C160";
    x1 <= x"0000E783";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 2: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 2: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 2: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 2: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 3
    w_we <= '1';
    w_addr <= "00001000";
    w_data <= x"0000C21A";
    x_we <= '1';
    x_k <= "11";
    x0 <= x"0000C228";
    x1 <= x"000076B5";
    x_go <= '0';
    y_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 3: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 3: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 3: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 3: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 4
    w_we <= '0';
    w_addr <= "00000100";
    w_data <= x"00004C06";
    x_we <= '0';
    x_k <= "01";
    x0 <= x"00005A5E";
    x1 <= x"00002CDB";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 4: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 4: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 4: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 4: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 5
    w_we <= '1';
    w_addr <= "00000010";
    w_data <= x"00009E9A";
    x_we <= '0';
    x_k <= "11";
    x0 <= x"0000BD83";
    x1 <= x"00000207";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 5: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 5: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 5: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 5: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 6
    w_we <= '0';
    w_addr <= "00000100";
    w_data <= x"00009D21";
    x_we <= '1';
    x_k <= "11";
    x0 <= x"00005C6C";
    x1 <= x"0000AC23";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 6: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 6: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 6: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 6: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 7
    w_we <= '1';
    w_addr <= "00001110";
    w_data <= x"0000A93E";
    x_we <= '1';
    x_k <= "01";
    x0 <= x"000098DF";
    x1 <= x"0000048B";
    x_go <= '1';
    y_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '0' then
      report "FAIL vector 7: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 7: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 7: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '1' then
      report "FAIL vector 7: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 8
    w_we <= '0';
    w_addr <= "00000001";
    w_data <= x"00009829";
    x_we <= '0';
    x_k <= "11";
    x0 <= x"00005604";
    x1 <= x"0000965E";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 8: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 8: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 8: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 8: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 9
    w_we <= '1';
    w_addr <= "00000011";
    w_data <= x"0000EE70";
    x_we <= '0';
    x_k <= "00";
    x0 <= x"000045AD";
    x1 <= x"00005F2F";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 9: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 9: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 9: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 9: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 10
    w_we <= '0';
    w_addr <= "00000111";
    w_data <= x"00009BCF";
    x_we <= '1';
    x_k <= "11";
    x0 <= x"0000935D";
    x1 <= x"00009220";
    x_go <= '0';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 10: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 10: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 10: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 10: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 11
    w_we <= '1';
    w_addr <= "00001110";
    w_data <= x"00003789";
    x_we <= '1';
    x_k <= "10";
    x0 <= x"0000E3DF";
    x1 <= x"0000F617";
    x_go <= '0';
    y_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 11: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 11: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 11: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 11: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 12
    w_we <= '0';
    w_addr <= "00001010";
    w_data <= x"00009F0C";
    x_we <= '0';
    x_k <= "01";
    x0 <= x"0000EE32";
    x1 <= x"00003DF3";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 12: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 12: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 12: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 12: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 13
    w_we <= '1';
    w_addr <= "00000110";
    w_data <= x"00000883";
    x_we <= '0';
    x_k <= "10";
    x0 <= x"00003C48";
    x1 <= x"0000D68F";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 13: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 13: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 13: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 13: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 14
    w_we <= '0';
    w_addr <= "00001110";
    w_data <= x"0000712A";
    x_we <= '1';
    x_k <= "00";
    x0 <= x"00000E9E";
    x1 <= x"0000A4BD";
    x_go <= '1';
    y_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '1' then
      report "FAIL vector 14: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"00000000" then
      report "FAIL vector 14: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 14: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '0' then
      report "FAIL vector 14: y_valid" severity error;
      errors := errors + 1;
    end if;
    -- vector 15
    w_we <= '1';
    w_addr <= "00000111";
    w_data <= x"00003668";
    x_we <= '1';
    x_k <= "11";
    x0 <= x"0000C994";
    x1 <= x"0000CD1F";
    x_go <= '1';
    y_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 12 loop
      tick;
    end loop;
    if x_ready /= '0' then
      report "FAIL vector 15: x_ready" severity error;
      errors := errors + 1;
    end if;
    if y0 /= x"2B97DE98" then
      report "FAIL vector 15: y0" severity error;
      errors := errors + 1;
    end if;
    if y1 /= x"00000000" then
      report "FAIL vector 15: y1" severity error;
      errors := errors + 1;
    end if;
    if y_valid /= '1' then
      report "FAIL vector 15: y_valid" severity error;
      errors := errors + 1;
    end if;
    if errors = 0 then
      report "PASS jev_tile_2x2: 16 vectors";
    else
      report "FAIL jev_tile_2x2: " & integer'image(errors) & " mismatches" severity failure;
    end if;
    finished <= true;
    wait;
  end process;
end architecture sim;
