`timescale 1ns/1ps
// jev_tile_2x2_tb.v -- self-checking testbench generated by the WASMApollo EDA; the expected
// values are the fabric's golden model (RefSim). Run: iverilog -o tb jev_tile_2x2.v jev_tile_2x2_tb.v && vvp tb

module jev_tile_2x2_tb;
  reg clk = 1'b0;
  reg rst = 1'b1;
  reg w_we = 0;
  reg [7:0] w_addr = 0;
  reg [31:0] w_data = 0;
  reg x_we = 0;
  reg [1:0] x_k = 0;
  reg [31:0] x0 = 0;
  reg [31:0] x1 = 0;
  reg x_go = 0;
  reg y_ready = 0;
  wire x_ready;
  wire [31:0] y0;
  wire [31:0] y1;
  wire y_valid;
  integer errors = 0;

  jev_tile_2x2 dut (.clk(clk), .rst(rst), .w_we(w_we), .w_addr(w_addr), .w_data(w_data), .x_we(x_we), .x_k(x_k), .x0(x0), .x1(x1), .x_go(x_go), .y_ready(y_ready), .x_ready(x_ready), .y0(y0), .y1(y1), .y_valid(y_valid));

  always #5 clk = ~clk;
  task tick;
    begin
      @(posedge clk);
      #1;
    end
  endtask

  initial begin
    // vector 0
    w_we = 1'h0;
    w_addr = 8'h0F;
    w_data = 32'h00007B06;
    x_we = 1'h0;
    x_k = 2'h2;
    x0 = 32'h00003AB5;
    x1 = 32'h000090B6;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 0: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 0: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 0: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 0: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 1
    w_we = 1'h1;
    w_addr = 8'h0D;
    w_data = 32'h000099B2;
    x_we = 1'h0;
    x_k = 2'h0;
    x0 = 32'h0000BC3B;
    x1 = 32'h00002B5E;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 1: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 1: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 1: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 1: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 2
    w_we = 1'h0;
    w_addr = 8'h04;
    w_data = 32'h0000B6EC;
    x_we = 1'h1;
    x_k = 2'h1;
    x0 = 32'h0000C160;
    x1 = 32'h0000E783;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 2: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 2: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 2: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 2: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 3
    w_we = 1'h1;
    w_addr = 8'h08;
    w_data = 32'h0000C21A;
    x_we = 1'h1;
    x_k = 2'h3;
    x0 = 32'h0000C228;
    x1 = 32'h000076B5;
    x_go = 1'h0;
    y_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 3: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 3: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 3: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 3: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 4
    w_we = 1'h0;
    w_addr = 8'h04;
    w_data = 32'h00004C06;
    x_we = 1'h0;
    x_k = 2'h1;
    x0 = 32'h00005A5E;
    x1 = 32'h00002CDB;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 4: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 4: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 4: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 4: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 5
    w_we = 1'h1;
    w_addr = 8'h02;
    w_data = 32'h00009E9A;
    x_we = 1'h0;
    x_k = 2'h3;
    x0 = 32'h0000BD83;
    x1 = 32'h00000207;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 5: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 5: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 5: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 5: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 6
    w_we = 1'h0;
    w_addr = 8'h04;
    w_data = 32'h00009D21;
    x_we = 1'h1;
    x_k = 2'h3;
    x0 = 32'h00005C6C;
    x1 = 32'h0000AC23;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 6: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 6: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 6: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 6: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 7
    w_we = 1'h1;
    w_addr = 8'h0E;
    w_data = 32'h0000A93E;
    x_we = 1'h1;
    x_k = 2'h1;
    x0 = 32'h000098DF;
    x1 = 32'h0000048B;
    x_go = 1'h1;
    y_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h0) begin $display("FAIL vector 7: x_ready = %h, want %h", x_ready, 1'h0); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 7: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 7: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h1) begin $display("FAIL vector 7: y_valid = %h, want %h", y_valid, 1'h1); errors = errors + 1; end
    // vector 8
    w_we = 1'h0;
    w_addr = 8'h01;
    w_data = 32'h00009829;
    x_we = 1'h0;
    x_k = 2'h3;
    x0 = 32'h00005604;
    x1 = 32'h0000965E;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 8: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 8: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 8: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 8: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 9
    w_we = 1'h1;
    w_addr = 8'h03;
    w_data = 32'h0000EE70;
    x_we = 1'h0;
    x_k = 2'h0;
    x0 = 32'h000045AD;
    x1 = 32'h00005F2F;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 9: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 9: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 9: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 9: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 10
    w_we = 1'h0;
    w_addr = 8'h07;
    w_data = 32'h00009BCF;
    x_we = 1'h1;
    x_k = 2'h3;
    x0 = 32'h0000935D;
    x1 = 32'h00009220;
    x_go = 1'h0;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 10: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 10: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 10: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 10: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 11
    w_we = 1'h1;
    w_addr = 8'h0E;
    w_data = 32'h00003789;
    x_we = 1'h1;
    x_k = 2'h2;
    x0 = 32'h0000E3DF;
    x1 = 32'h0000F617;
    x_go = 1'h0;
    y_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 11: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 11: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 11: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 11: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 12
    w_we = 1'h0;
    w_addr = 8'h0A;
    w_data = 32'h00009F0C;
    x_we = 1'h0;
    x_k = 2'h1;
    x0 = 32'h0000EE32;
    x1 = 32'h00003DF3;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 12: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 12: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 12: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 12: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 13
    w_we = 1'h1;
    w_addr = 8'h06;
    w_data = 32'h00000883;
    x_we = 1'h0;
    x_k = 2'h2;
    x0 = 32'h00003C48;
    x1 = 32'h0000D68F;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 13: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 13: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 13: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 13: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 14
    w_we = 1'h0;
    w_addr = 8'h0E;
    w_data = 32'h0000712A;
    x_we = 1'h1;
    x_k = 2'h0;
    x0 = 32'h00000E9E;
    x1 = 32'h0000A4BD;
    x_go = 1'h1;
    y_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h1) begin $display("FAIL vector 14: x_ready = %h, want %h", x_ready, 1'h1); errors = errors + 1; end
    if (y0 !== 32'h00000000) begin $display("FAIL vector 14: y0 = %h, want %h", y0, 32'h00000000); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 14: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h0) begin $display("FAIL vector 14: y_valid = %h, want %h", y_valid, 1'h0); errors = errors + 1; end
    // vector 15
    w_we = 1'h1;
    w_addr = 8'h07;
    w_data = 32'h00003668;
    x_we = 1'h1;
    x_k = 2'h3;
    x0 = 32'h0000C994;
    x1 = 32'h0000CD1F;
    x_go = 1'h1;
    y_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (12) tick;
    if (x_ready !== 1'h0) begin $display("FAIL vector 15: x_ready = %h, want %h", x_ready, 1'h0); errors = errors + 1; end
    if (y0 !== 32'h2B97DE98) begin $display("FAIL vector 15: y0 = %h, want %h", y0, 32'h2B97DE98); errors = errors + 1; end
    if (y1 !== 32'h00000000) begin $display("FAIL vector 15: y1 = %h, want %h", y1, 32'h00000000); errors = errors + 1; end
    if (y_valid !== 1'h1) begin $display("FAIL vector 15: y_valid = %h, want %h", y_valid, 1'h1); errors = errors + 1; end
    if (errors == 0) $display("PASS jev_tile_2x2: 16 vectors");
    else $display("FAIL jev_tile_2x2: %0d mismatches", errors);
    $finish;
  end
endmodule
